"""data

Revision ID: 21b3d671a45f
Revises: 65487bc60d77
Create Date: 2020-03-04 10:56:08.288253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b3d671a45f'
down_revision = '65487bc60d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'time')
    # ### end Alembic commands ###
